Komodo.Ui/Models/Commodity/CommodityGroup.cs
// - Required Assemblies
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Komodo.Ui.Models.Commodity
{
  public class CommodityGroup
  {
    #region Properties

    public int CommodityGroupId { get; set; }

    [Required]
    [Display(Name="Group Code: ")]
    [MaxLength(10,ErrorMessage = "Group Code cannot exceed 10 characters")]
    public string CommodityGroupCode { get; set; }

    [Required]
    [Display(Name ="Group Description: ")]
    public string CommodityGroupDescription { get; set; }

    public List<Commodity> Commodities { get; set; }

    #endregion

    #region Construct

    public CommodityGroup()
    {
      Commodities = new List<Commodity>();
    }

    #endregion
  }
}

Komodo.Ui/Controllers/CommodityGroupController.cs
// - Required Assemblies
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;

// - Application Assemblies
using Komodo.Ui.Models.Commodity;
using Komodo.Ui.Repositories.Commodity;
using Komodo.Ui.ViewModels;

namespace Komodo.Ui.Controllers
{
  public class CommodityGroupController : Controller
  {
    #region ClassVariables

    private ICommodityRepository mc_CommodityRepository;

    #endregion

    #region Construct

    public CommodityGroupController(ICommodityRepository commodityRepository)
    {
      mc_CommodityRepository = commodityRepository;
    }

    #endregion

    #region PublicMethods

    [HttpGet]
    public ViewResult Index()
    {
      var commodityGroupIndexViewModel = new CommodityGroupIndexViewModel();

      var getCommodityGroupsResult = mc_CommodityRepository.GetCommodityGroups("");
      commodityGroupIndexViewModel.CommodityGroups = getCommodityGroupsResult.Result as List<CommodityGroup>;

      return View(commodityGroupIndexViewModel);
    }

    [HttpGet]
    [Route("/{controller}/get/{commoditygroupid:int}")]
    public ViewResult Details(int commodityGroupId)
    {
      var getCommidityGroupResult = mc_CommodityRepository.GetCommodityGroup(commodityGroupId);
      var commodityGroup = getCommidityGroupResult.Result as CommodityGroup;

      return View(commodityGroup);
    }

    [HttpGet]
    public ViewResult Create()
    {
      var commodityGroup = new CommodityGroup();

      return View("Save",commodityGroup);
    }

    [HttpGet]
    public ViewResult Update(int commodityGroupId)
    {
      var commodityGroupResult = mc_CommodityRepository.GetCommodityGroup(commodityGroupId);
      var commodityGroup       = commodityGroupResult.Result as CommodityGroup;

      return View("Save", commodityGroup);
    }

    [HttpGet]
    [Route("/{controller}/delete/commoditygroupid:int")]
    public ViewResult Delete(int commodityGroupId)
    {
      CommodityGroup commodityGroupUndo;

      var commodityGroupUndoResult = mc_CommodityRepository.DeleteCommodityGroup(commodityGroupId);
      commodityGroupUndo = commodityGroupUndoResult.Result as CommodityGroup;

      return View("Save",commodityGroupUndo);
    }

    [HttpPost]
    public IActionResult Save(CommodityGroup commodityGroup)
    {
      CommodityGroup commodityGroupSaved;

      if (ModelState.IsValid)
      {
        if (commodityGroup.CommodityGroupId < 1)
        {
          var commodityGroupCreatedResult = mc_CommodityRepository.CreateCommodityGroup(commodityGroup);
          commodityGroupSaved = commodityGroupCreatedResult.Result as CommodityGroup;
        }
        else
        {
          var commodityGroupUpdatedResult = mc_CommodityRepository.UpdateCommodityGroup(commodityGroup);
          commodityGroupSaved = commodityGroupUpdatedResult.Result as CommodityGroup;
        }

        return View("Details", commodityGroupSaved);
      }

      // - Someting went wrong. Try again!
      return View("Save",commodityGroup);
    }

    #endregion
  }
}

Komodo.Ui/Views/CommodityGroup/Details.cshtml
@model Komodo.Ui.Models.Commodity.CommodityGroup

@{
  ViewBag.Title = "Commodity Group Details";
}

<div class="form-group row">
  Commodity Group Id : @Model.CommodityGroupId
</div>
<div class="form-group row">
  Commodity Group Code : @Model.CommodityGroupCode
</div>
<div class="form-group row">
  Commodity Group Description : @Model.CommodityGroupDescription
</div>
<div class="form-group row">
  <div class="table">
    <div class="row-cols-3">
      <div class="col-4">
        <a asp-controller="CommodityGroup" asp-action="Index" class="btn btn-info">Groups</a>
      </div>
      <div class="col-4">
        <a asp-controller="CommodityGroup" asp-action="Update" asp-route-commodityGroupId="@Model.CommodityGroupId" class="btn btn-primary">Edit</a>
      </div>
      <div class="col-4">
        <a asp-controller="CommodityGroup" asp-action="Delete" asp-route-commodityGroupId="@Model.CommodityGroupId" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>

Komodo.Ui/Views/CommodityGroup/Index.cshtml
@model Komodo.Ui.ViewModels.CommodityGroupIndexViewModel

@{
  ViewBag.Title = "Commodity Groups";
}

<div class="container">
  <div class="row">
    <div class="col-7 float-right">
      <label asp-for="FilterDescription" class="col-form-label"></label>
    </div>
    <div class="col-3">
      <input asp-for="FilterDescription" class="form-control" placeholder="Filter Description" />
    </div>
    <div class="col-2">
      <button type="submit" class="btn-primary">Filter</button>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      Commodities
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="table" style="width:100%">
        <div class="row">
          <div class="col-2">Code</div>
          <div class="col-9">Description</div>
          <div class="col-1 text-center">Action</div>
        </div>
        @foreach (var commodityGroup in Model.CommodityGroups)
        {
          <div class="row justify-content-center">
            <div class="col-2">@commodityGroup.CommodityGroupCode</div>
            <div class="col-9">@commodityGroup.CommodityGroupDescription</div>
            <div class="col-1 text-center">
              <a asp-controller="CommodityGroup" asp-action="Details" asp-route-commoditygroupid="@commodityGroup.CommodityGroupId" class="btn-sm btn-primary m-1">View</a>
            </div>
          </div>
        }
      </div>
    </div>
  </div>
</div>

Komodo.Ui/Views/CommodityGroup/Save.cshtml
@model Komodo.Ui.Models.Commodity.CommodityGroup

@{
  ViewBag.Title = "Commodity Group Save";
}

<form asp-controller="CommodityGroup" asp-action="Save" method="post" class="mt-3">
  <input hidden asp-for="CommodityGroupId"/>
  <div class="form-group row">
    <label asp-for="CommodityGroupCode" class="col-sm-2 col-form-label"></label>
    <div class="col-sm-10">
      <input asp-for="CommodityGroupCode" class="form-control" placeholder="Code"/>
      <span asp-for="CommodityGroupCode" class="text-danger"></span>
    </div>
  </div>
  <div class="form-group row">
    <label asp-for="CommodityGroupDescription" class="col-sm-2 col-form-label"></label>
    <div class="col-sm-10">
      <input asp-for="CommodityGroupDescription" class="form-control" placeholder="Description"/>
      <span asp-for="CommodityGroupDescription" class="text-danger"></span>
    </div>
  </div>
  <div asp-validation-summary="All" class="text-danger"></div>
  <div class="form-group row">
    <div class="table">
      <div class="row-cols-2">
        <div class="col-6">
          <a asp-controller="CommodityGroup" asp-action="Index" class="btn btn-info">Groups</a>
        </div>
        <div class="col-6">
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
      </div>
    </div>
  </div>
</form>