Komodo.Ui/Models/Commodity/Commodity.cs
// - Required Assemblies
using System.ComponentModel.DataAnnotations;

// - Application Assemblies

namespace Komodo.Ui.Models.Commodity
{
  public class Commodity
  {
    public int CommodityId { get; set; }

    [Required]
    [Display(Name = "Commodity Code:")]
    [MaxLength(10,ErrorMessage = "Commodity Code cannot exceed 10 characters")]
    public string CommodityCode { get; set; }

    [Required]
    [Display(Name = "Description:")]
    public string CommodityDescription { get; set; }

    [Display(Name="Commodity Group:")]
    public int CommodityGroupId { get; set; }
  }
}

Komodo.Ui/Models/Commodity/CommodityGroup.cs
// - Required Assemblies
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Komodo.Ui.Models.Commodity
{
  public class CommodityGroup
  {
    #region Properties

    public int CommodityGroupId { get; set; }

    [Required]
    [Display(Name="Group Code: ")]
    [MaxLength(10,ErrorMessage = "Group Code cannot exceed 10 characters")]
    public string CommodityGroupCode { get; set; }

    [Required]
    [Display(Name ="Group Description: ")]
    public string CommodityGroupDescription { get; set; }

    public List<Commodity> Commodities { get; set; }

    #endregion

    #region Construct

    public CommodityGroup()
    {
      Commodities = new List<Commodity>();
    }

    #endregion
  }
}

Komodo.Ui/ViewModels/CommodityViewModel.cs
// - Required Assemblies

// - Application Assemblies
using Komodo.Ui.Models.Commodity;

namespace Komodo.Ui.ViewModels
{
  /// <summary>
  /// - This class is used to present the Commodity.
  /// - It includes the full CommodityGroup(parent) of the
  ///   Commodity where One Commodity can only belong to
  ///   one CommodityGroup while one CommodityGroup can
  ///   have multiple Commodities
  /// </summary>
  public class CommodityViewModel : Commodity
  {
    public string CommodityGroupCode { get; set; }
    public string CommodityGroupDescription { get; set; }

    public CommodityViewModel()
    {
      ;
    }

    public CommodityViewModel(int commodityId, 
                              string commodityCode, 
                              string commodityDescription, 
                              int commodityGroupId, 
                              string commodityGroupCode,
                              string commodityGroupDescription)
    {
      CommodityId = commodityId;
      CommodityCode = commodityCode;
      CommodityDescription = commodityDescription;
      CommodityGroupId = commodityGroupId;
      CommodityGroupCode = commodityGroupCode;
      CommodityGroupDescription = commodityGroupDescription;
    }
  }
}

Komodo.Ui/Controllers/CommodityController.cs
// - Required Assemblies
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;

// - Application Assemblies
using Komodo.Ui.Models.Commodity;
using Komodo.Ui.Repositories.Commodity;
using Komodo.Ui.ViewModels;

namespace Komodo.Ui.Controllers
{
  public class CommodityController : Controller
  {
    #region ClassVariables

    private ICommodityRepository mc_CommodityRepository;

    #endregion

    #region Construct

    public CommodityController(ICommodityRepository commodityRepository)
    {
      mc_CommodityRepository = commodityRepository;
    }

    #endregion

    #region Public Methods

    [HttpGet]
    public ViewResult Index()
    {
      var getCommoditiesResult = mc_CommodityRepository.GetCommodities("");
      var commodities = getCommoditiesResult.Result as List<Commodity>;

      var retCommodityGroupsResult = mc_CommodityRepository.GetCommodityGroups("");
      var commodityGroups = retCommodityGroupsResult.Result as List<CommodityGroup>;

      var commodityViewModels = BuildCommodityViewModels(commodityGroups, commodities) as List<CommodityViewModel>;
      var commodityIndexViewModel = new CommodityIndexViewModel(commodityViewModels,commodityGroups);

      return View(commodityIndexViewModel);
    }

    [HttpGet]
    [Route("/{controller}/details/{commodityId:int}")]
    public ViewResult Details(int commodityId)
    {
      var getCommodityResult = mc_CommodityRepository.GetCommodity(commodityId);
      var commodity = getCommodityResult.Result as Commodity;

      return View(commodity);
    }

    [HttpGet]
    [Route("/{controller}/create")]
    public ViewResult Create()
    {
      var commoditySaveViewModel = new CommoditySaveViewModel();
      var commodityGroupsResult = mc_CommodityRepository.GetCommodityGroups("");
      commoditySaveViewModel.CommodityGroups = commodityGroupsResult.Result as List<CommodityGroup>;

      return View("Save",commoditySaveViewModel);
    }

    [HttpGet]
    [Route("/{controller}/update/{commodityId:int}")]
    public ViewResult Update(int commodityId)
    {
      // - ViewModel to combine all the data items required
      //   to update the Commodity
      var commoditySaveViewModel = new CommoditySaveViewModel();
      var commodityResult = mc_CommodityRepository.GetCommodity(commodityId);
      var commodity = commodityResult.Result as Commodity;
      var commodityGroupsResult = mc_CommodityRepository.GetCommodityGroups("");
      var commodityGroups = commodityGroupsResult.Result as List<CommodityGroup>;
      commoditySaveViewModel.Commodity = commodity;
      commoditySaveViewModel.CommodityGroups = commodityGroups;

      return View("Save", commoditySaveViewModel);
    }

    [HttpGet]
    [Route("/{controller}/delete/{commodityId:int}")]
    public ViewResult Delete(int commodityId)
    {
      var commoditySaveViewModel = new CommoditySaveViewModel();

      var commodityUndoResult = mc_CommodityRepository.DeleteCommodity(commodityId);
      commoditySaveViewModel.Commodity = commodityUndoResult.Result as Commodity;

      var commodityGroupsResult = mc_CommodityRepository.GetCommodityGroups("");
      commoditySaveViewModel.CommodityGroups = commodityGroupsResult.Result as List<CommodityGroup>;

      return View("Save", commoditySaveViewModel);
    }

    [HttpPost]
    [Route("/{controller}/create")]
    public IActionResult Save(Commodity commodity)
    {
      Commodity commoditySaved;

      if (ModelState.IsValid)
      {
        if (commodity.CommodityId < 1)
        {
          var commodityCreatedResult = mc_CommodityRepository.CreateCommodity(commodity);
          commoditySaved = commodityCreatedResult.Result as Commodity;
        }
        else
        {
          var commodityUpdatedResult = mc_CommodityRepository.UpdateCommodity(commodity);
          commoditySaved = commodityUpdatedResult.Result as Commodity;
        }

        return View("Details", commoditySaved);
      }

      // - Houston we have a problem...
      // - Major Tom to ground control: lets go back home.
      var commoditySaveViewModel = new CommoditySaveViewModel();
      var commodityGroupsResult  = mc_CommodityRepository.GetCommodityGroups("");
      commoditySaveViewModel.CommodityGroups = commodityGroupsResult.Result as List<CommodityGroup>;

      return View("Save",commoditySaveViewModel);
    }

    #endregion

    #region PrivateMethods

    private List<CommodityViewModel> BuildCommodityViewModels(List<CommodityGroup> commodityGroups, List<Commodity> commodities)
    {
      List<CommodityViewModel> commodityViewModels = (from Cmd in commodities
                                                      join CmdGrp in commodityGroups on Cmd.CommodityGroupId equals CmdGrp.CommodityGroupId
                                                      select new CommodityViewModel()
                                                      {
                                                        CommodityId = Cmd.CommodityId,
                                                        CommodityCode = Cmd.CommodityCode,
                                                        CommodityDescription = Cmd.CommodityDescription,
                                                        CommodityGroupId = Cmd.CommodityGroupId,
                                                        CommodityGroupCode = CmdGrp.CommodityGroupCode,
                                                        CommodityGroupDescription = CmdGrp.CommodityGroupDescription
                                                      }).ToList();

      return commodityViewModels;
    }

    #endregion
  }
}

Komodo.Ui/Views/Commodity/Details.cshtml
@model Komodo.Ui.Models.Commodity.Commodity

@{
  ViewBag.Title = "Commodity Details";
}

<div class="form-group row">
  Commodity Id : @Model.CommodityId
</div>
<div class="form-group row">
  Commodity Code : @Model.CommodityCode
</div>
<div class="form-group row">
  Commodity Description : @Model.CommodityDescription
</div>
<div class="form-group row">
  Commodity Group : @Model.CommodityGroupId
</div>
<div class="form-group row">
  <div class="table">
    <div class="row-cols-3">
      <div class="col-4">
        <a asp-controller="Commodity" asp-action="Index" class="btn btn-info">Commodities</a>
      </div>
      <div class="col-4">
        <a asp-controller="Commodity" asp-action="Update" class="btn btn-primary" asp-route-commodityId="@Model.CommodityId">Edit</a>
      </div>
      <div class="col-4">
        <a asp-controller="Commodity" asp-action="Delete" class="btn btn-danger" asp-route-commodityId="@Model.CommodityId">Delete</a>
      </div>
    </div>
  </div>
</div>

Komodo.Ui/Views/Commodity/Index.cshtml
@model Komodo.Ui.ViewModels.CommodityIndexViewModel

@{
  ViewBag.Title = "Commodities";
}

<div class="container">
  <div class="row">
    <div class="col-2">
      <label asp-for="CommodityGroups" class="col-form-label"></label>
    </div>
    <div class="col-3">
      [Group Selector here]
    </div>
    <div class="col-2">
      <label asp-for="FilterDescription" class="col-form-label"></label>
    </div>
    <div class="col-3">
      <input asp-for="FilterDescription" class="form-control" placeholder="Filter Description" />
    </div>
    <div class="col-2">
      <button type="submit" class="btn-primary">Filter</button>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      Commodities
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="table" style="width: 100%">
        <div class="row">
          <div class="col-2">Code</div>
          <div class="col-7">Description</div>
          <div class="col-2">Group</div>
          <div class="col-1 text-center">Action</div>
        </div>
        @foreach (var commodityViewModel in Model.CommodityViewModels)
        {
          <div class="row justify-content-center">
            <div class="col-2">@commodityViewModel.CommodityCode</div>
            <div class="col-7">@commodityViewModel.CommodityDescription</div>
            <div class="col-2">@commodityViewModel.CommodityGroupCode</div>
            <div class="col-1 text-center">
              <a asp-controller="Commodity" asp-action="Details" asp-route-commodityId="@commodityViewModel.CommodityId" class="btn-sm btn-primary m-1">View</a>
            </div>
          </div>
        }
      </div>
    </div>
  </div>
</div>

Komodo.Ui/Views/Commodity/Save.cshtml
@model Komodo.Ui.ViewModels.CommoditySaveViewModel

@{
  ViewBag.Title = "Commodity Save";
}

<form asp-controller="Commodity" asp-action="Save" method="post" class="mt-3">
  <input hidden asp-for="Commodity.CommodityId"/>
  <div class="form-group row">
    <label asp-for="Commodity.CommodityCode" class="col-sm-2 col-form-label"></label>
    <div class="col-sm-10">
      <input asp-for="Commodity.CommodityCode" class="form-control" placeholder="Code"/>
      <span asp-for="Commodity.CommodityCode" class="text-danger"></span>
    </div>
  </div>
  <div class="form-group row">
    <label asp-for="Commodity.CommodityDescription" class="col-sm-2 col-form-label"></label>
    <div class="col-sm-10">
      <input asp-for="Commodity.CommodityDescription" class="form-control" placeholder="Commodity"/>
      <span asp-for="Commodity.CommodityDescription" class="text-danger"></span>
    </div>
  </div>
  <div class="form-group row">
    <label asp-for="Commodity.CommodityGroupId" clas="col-sm-2 col-form-label"></label>
    <div class="col-sm-10">
      <input asp-for="Commodity.CommodityGroupId" class="form-control"/>
    </div>
  </div>
  <div asp-validation-summary="All" class="text-danger"></div>
  <div class="form-group row">
    <div class="table">
      <div class="row-cols-2">
        <div class="col-6">
          <a asp-controller="Commodity" asp-action="Index" class="btn btn-info">Commodities</a>
        </div>
        <div class="col-6">
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
      </div>
    </div>
  </div>
</form>